In [50]:
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine

In [51]:
load_dotenv

<function dotenv.main.load_dotenv(dotenv_path: str | ForwardRef('os.PathLike[str]') | None = None, stream: IO[str] | None = None, verbose: bool = False, override: bool = False, interpolate: bool = True, encoding: str | None = 'utf-8') -> bool>

In [52]:
password = os.getenv('DB_PASSWORD')
engine = create_engine(f'postgresql://postgres:{password}@localhost:5432/catastrophe_risk')

In [53]:
import pandas as pd
pd.read_sql('SELECT * FROM catastrophe', engine)

,event_id,event_time,magnitude,depth_km,latitude,longitude,place,risk_tier
0,us6000tg95,2026-07-27 23:12:12.908,5.1,10.000,-24.7784,-175.2557,south of Tonga,Moderate
1,us6000tg94,2026-07-27 23:06:34.085,5.3,71.061,7.6738,126.7653,"23 km E of Kinablangan, Philippines",Moderate
2,us6000tg8z,2026-07-27 22:32:02.648,5.0,10.000,-7.5058,-13.4844,"112 km ENE of Georgetown, Saint Helena",Low
3,us6000tg6e,2026-07-27 19:03:38.391,4.5,426.772,28.1222,139.8936,"Bonin Islands, Japan region",Low
4,us6000tg5f,2026-07-27 17:47:01.325,4.5,116.626,36.6101,71.5913,"9 km SSE of Ashkāsham, Afghanistan",Low
...,...,...,...,...,...,...,...,...
572,us6000t8se,2026-06-28 03:39:21.783,4.6,10.000,37.9587,95.4541,"254 km SSE of Dunhuang, China",Low
573,us6000t8sa,2026-06-28 03:18:41.117,4.5,10.000,51.9357,176.2034,"229 km ESE of Attu Station, Alaska",Low
574,us6000t8s6,2026-06-28 02:59:20.784,5.1,76.884,-6.4130,147.7124,"21 km NW of Finschhafen, Papua New Guinea",Moderate
575,us6000tag6,2026-06-28 02:39:47.687,4.7,10.000,-9.7274,159.3959,"35 km W of Malango, Solomon Islands",Low
576,us6000t8xg,2026-06-28 02:22:10.778,4.6,10.000,-13.3173,-111.1977,central East Pacific Rise,Low

In [54]:
import requests
response = requests.get("https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&starttime=2026-06-28&endtime=2026-07-28&minmagnitude=4.5")

In [55]:
response.status_code

200

In [56]:
data = response.json()

In [57]:
data['features'][10]

{'type': 'Feature',
 'properties': {'mag': 5.4,
  'place': '82 km SSW of San Pedro de Atacama, Chile',
  'time': 1785142663758,
  'updated': 1785229400371,
  'tz': None,
  'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000t3m7',
  'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000t3m7&format=geojson',
  'felt': 4,
  'cdi': 2.2,
  'mmi': 4.189,
  'alert': 'green',
  'status': 'reviewed',
  'tsunami': 0,
  'sig': 449,
  'net': 'us',
  'code': '7000t3m7',
  'ids': ',us7000t3m7,usauto7000t3m7,',
  'sources': ',us,usauto,',
  'types': ',dyfi,internal-moment-tensor,losspager,origin,phase-data,shakemap,',
  'nst': 52,
  'dmin': 0.723,
  'rms': 1.4,
  'gap': 56,
  'magType': 'mb',
  'type': 'earthquake',
  'title': 'M 5.4 - 82 km SSW of San Pedro de Atacama, Chile'},
 'geometry': {'type': 'Point', 'coordinates': [-68.633, -23.5454, 106.991]},
 'id': 'us7000t3m7'}

In [58]:
data['features'][10]['geometry']

{'type': 'Point', 'coordinates': [-68.633, -23.5454, 106.991]}

In [59]:
len(data['features'])

577

In [60]:
sample_time = data['features'][10]['properties']['time']
sample_time

1785142663758

In [61]:
pd.to_datetime(sample_time, unit='ms')

Timestamp('2026-07-27 08:57:43.758000')

In [62]:
empty_list=[]

for feature in data['features']:
    event_dict = {

    "event_id": feature['id'],
    "magnitude": feature['properties']['mag'],
    "place": feature['properties']['place'],
    "event_time": pd.to_datetime(feature['properties']['time'], unit='ms'),
    "longitude": feature['geometry']['coordinates'][0],
    "latitude": feature['geometry']['coordinates'][1],
    "depth_km": feature['geometry']['coordinates'][2]
    }
    empty_list.append(event_dict)
pd.DataFrame(empty_list)

,event_id,magnitude,place,event_time,longitude,latitude,depth_km
0,us6000tg95,5.1,south of Tonga,2026-07-27 23:12:12.908,-175.2557,-24.7784,10.000
1,us6000tg94,5.3,"23 km E of Kinablangan, Philippines",2026-07-27 23:06:34.085,126.7653,7.6738,71.061
2,us6000tg8z,5.0,"112 km ENE of Georgetown, Saint Helena",2026-07-27 22:32:02.648,-13.4844,-7.5058,10.000
3,us6000tg6e,4.5,"Bonin Islands, Japan region",2026-07-27 19:03:38.391,139.8936,28.1222,426.772
4,us6000tg5f,4.5,"9 km SSE of Ashkāsham, Afghanistan",2026-07-27 17:47:01.325,71.5913,36.6101,116.626
...,...,...,...,...,...,...,...
572,us6000t8se,4.6,"254 km SSE of Dunhuang, China",2026-06-28 03:39:21.783,95.4541,37.9587,10.000
573,us6000t8sa,4.5,"229 km ESE of Attu Station, Alaska",2026-06-28 03:18:41.117,176.2034,51.9357,10.000
574,us6000t8s6,5.1,"21 km NW of Finschhafen, Papua New Guinea",2026-06-28 02:59:20.784,147.7124,-6.4130,76.884
575,us6000tag6,4.7,"35 km W of Malango, Solomon Islands",2026-06-28 02:39:47.687,159.3959,-9.7274,10.000
576,us6000t8xg,4.6,central East Pacific Rise,2026-06-28 02:22:10.778,-111.1977,-13.3173,10.000

In [63]:
df_earthquakes = pd.DataFrame(empty_list)

In [64]:
df_earthquakes.shape

(577, 7)

In [65]:
df_earthquakes.head(5)

,event_id,magnitude,place,event_time,longitude,latitude,depth_km
0,us6000tg95,5.1,south of Tonga,2026-07-27 23:12:12.908,-175.2557,-24.7784,10.000
1,us6000tg94,5.3,"23 km E of Kinablangan, Philippines",2026-07-27 23:06:34.085,126.7653,7.6738,71.061
2,us6000tg8z,5.0,"112 km ENE of Georgetown, Saint Helena",2026-07-27 22:32:02.648,-13.4844,-7.5058,10.000
3,us6000tg6e,4.5,"Bonin Islands, Japan region",2026-07-27 19:03:38.391,139.8936,28.1222,426.772
4,us6000tg5f,4.5,"9 km SSE of Ashkāsham, Afghanistan",2026-07-27 17:47:01.325,71.5913,36.6101,116.626

In [66]:
df_earthquakes.describe

<bound method NDFrame.describe of        event_id  magnitude                                      place  \
0    us6000tg95        5.1                             south of Tonga
1    us6000tg94        5.3        23 km E of Kinablangan, Philippines
2    us6000tg8z        5.0     112 km ENE of Georgetown, Saint Helena
3    us6000tg6e        4.5                Bonin Islands, Japan region
4    us6000tg5f        4.5         9 km SSE of Ashkāsham, Afghanistan
..          ...        ...                                        ...
572  us6000t8se        4.6              254 km SSE of Dunhuang, China
573  us6000t8sa        4.5         229 km ESE of Attu Station, Alaska
574  us6000t8s6        5.1  21 km NW of Finschhafen, Papua New Guinea
575  us6000tag6        4.7        35 km W of Malango, Solomon Islands
576  us6000t8xg        4.6                  central East Pacific Rise

                 event_time  longitude  latitude  depth_km
0   2026-07-27 23:12:12.908  -175.2557  -24.7784    10.000
1   2026-07-27 23:06:34.085   126.7653    7.6738    71.061
2   2026-07-27 22:32:02.648   -13.4844   -7.5058    10.000
3   2026-07-27 19:03:38.391   139.8936   28.1222   426.772
4   2026-07-27 17:47:01.325    71.5913   36.6101   116.626
..                      ...        ...       ...       ...
572 2026-06-28 03:39:21.783    95.4541   37.9587    10.000
573 2026-06-28 03:18:41.117   176.2034   51.9357    10.000
574 2026-06-28 02:59:20.784   147.7124   -6.4130    76.884
575 2026-06-28 02:39:47.687   159.3959   -9.7274    10.000
576 2026-06-28 02:22:10.778  -111.1977  -13.3173    10.000

[577 rows x 7 columns]>

In [67]:

bins = [0, 5.0, 6.0, 10]
labels = ['Low', 'Moderate', 'High']
df_earthquakes['risk_tier'] = pd.cut(df_earthquakes['magnitude'], bins=bins, labels=labels)

In [68]:
df_earthquakes['risk_tier'].value_counts()

risk_tier
Low         440
Moderate    129
High          8
Name: count, dtype: int64

## Loading the ETL

In [69]:
df_earthquakes.to_sql('catastrophe', engine, if_exists='append', index=False)

DatabaseError: Execution failed on sql 'INSERT INTO catastrophe (event_id, magnitude, place, event_time, longitude, latitude, depth_km, risk_tier) VALUES (:event_id, :magnitude, :place, :event_time, :longitude, :latitude, :depth_km, :risk_tier)': (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "catastrophe_pkey"
DETAIL:  Key (event_id)=(us6000tg95) already exists.

[SQL: INSERT INTO catastrophe (event_id, magnitude, place, event_time, longitude, latitude, depth_km, risk_tier) VALUES (%(event_id__0)s, %(magnitude__0)s, %(place__0)s, %(event_time__0)s, %(longitude__0)s, %(latitude__0)s, %(depth_km__0)s, %(risk_tier__0) ... 88894 characters truncated ... , %(event_time__576)s, %(longitude__576)s, %(latitude__576)s, %(depth_km__576)s, %(risk_tier__576)s)]
[parameters: {'place__0': 'south of Tonga', 'event_time__0': datetime.datetime(2026, 7, 27, 23, 12, 12, 908000), 'depth_km__0': 10.0, 'event_id__0': 'us6000tg95', 'longitude__0': -175.2557, 'latitude__0': -24.7784, 'magnitude__0': 5.1, 'risk_tier__0': 'Moderate', 'place__1': '23 km E of Kinablangan, Philippines', 'event_time__1': datetime.datetime(2026, 7, 27, 23, 6, 34, 85000), 'depth_km__1': 71.061, 'event_id__1': 'us6000tg94', 'longitude__1': 126.7653, 'latitude__1': 7.6738, 'magnitude__1': 5.3, 'risk_tier__1': 'Moderate', 'place__2': '112 km ENE of Georgetown, Saint Helena', 'event_time__2': datetime.datetime(2026, 7, 27, 22, 32, 2, 648000), 'depth_km__2': 10.0, 'event_id__2': 'us6000tg8z', 'longitude__2': -13.4844, 'latitude__2': -7.5058, 'magnitude__2': 5.0, 'risk_tier__2': 'Low', 'place__3': 'Bonin Islands, Japan region', 'event_time__3': datetime.datetime(2026, 7, 27, 19, 3, 38, 391000), 'depth_km__3': 426.772, 'event_id__3': 'us6000tg6e', 'longitude__3': 139.8936, 'latitude__3': 28.1222, 'magnitude__3': 4.5, 'risk_tier__3': 'Low', 'place__4': '9 km SSE of Ashkāsham, Afghanistan', 'event_time__4': datetime.datetime(2026, 7, 27, 17, 47, 1, 325000), 'depth_km__4': 116.626, 'event_id__4': 'us6000tg5f', 'longitude__4': 71.5913, 'latitude__4': 36.6101, 'magnitude__4': 4.5, 'risk_tier__4': 'Low', 'place__5': '206 km W of Abepura, Indonesia', 'event_time__5': datetime.datetime(2026, 7, 27, 15, 51, 33, 601000), 'depth_km__5': 10.0, 'event_id__5': 'us6000tg2t', 'longitude__5': 138.7744, 'latitude__5': -2.5548, 'magnitude__5': 4.9, 'risk_tier__5': 'Low', 'place__6': '147 km E of Kimbe, Papua New Guinea', 'event_time__6': datetime.datetime(2026, 7, 27, 14, 33, 36, 219000) ... 4516 parameters truncated ... 'magnitude__570': 5.1, 'risk_tier__570': 'Moderate', 'place__571': '46 km ENE of Noda, Japan', 'event_time__571': datetime.datetime(2026, 6, 28, 5, 39, 32, 677000), 'depth_km__571': 53.117, 'event_id__571': 'us6000t8si', 'longitude__571': 142.3415, 'latitude__571': 40.2134, 'magnitude__571': 4.5, 'risk_tier__571': 'Low', 'place__572': '254 km SSE of Dunhuang, China', 'event_time__572': datetime.datetime(2026, 6, 28, 3, 39, 21, 783000), 'depth_km__572': 10.0, 'event_id__572': 'us6000t8se', 'longitude__572': 95.4541, 'latitude__572': 37.9587, 'magnitude__572': 4.6, 'risk_tier__572': 'Low', 'place__573': '229 km ESE of Attu Station, Alaska', 'event_time__573': datetime.datetime(2026, 6, 28, 3, 18, 41, 117000), 'depth_km__573': 10.0, 'event_id__573': 'us6000t8sa', 'longitude__573': 176.2034, 'latitude__573': 51.9357, 'magnitude__573': 4.5, 'risk_tier__573': 'Low', 'place__574': '21 km NW of Finschhafen, Papua New Guinea', 'event_time__574': datetime.datetime(2026, 6, 28, 2, 59, 20, 784000), 'depth_km__574': 76.884, 'event_id__574': 'us6000t8s6', 'longitude__574': 147.7124, 'latitude__574': -6.413, 'magnitude__574': 5.1, 'risk_tier__574': 'Moderate', 'place__575': '35 km W of Malango, Solomon Islands', 'event_time__575': datetime.datetime(2026, 6, 28, 2, 39, 47, 687000), 'depth_km__575': 10.0, 'event_id__575': 'us6000tag6', 'longitude__575': 159.3959, 'latitude__575': -9.7274, 'magnitude__575': 4.7, 'risk_tier__575': 'Low', 'place__576': 'central East Pacific Rise', 'event_time__576': datetime.datetime(2026, 6, 28, 2, 22, 10, 778000), 'depth_km__576': 10.0, 'event_id__576': 'us6000t8xg', 'longitude__576': -111.1977, 'latitude__576': -13.3173, 'magnitude__576': 4.6, 'risk_tier__576': 'Low'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [ ]:
pd.read_sql('SELECT * FROM catastrophe', engine)

,event_id,event_time,magnitude,depth_km,latitude,longitude,place,risk_tier
0,us6000tg95,2026-07-27 23:12:12.908,5.1,10.000,-24.7784,-175.2557,south of Tonga,Moderate
1,us6000tg94,2026-07-27 23:06:34.085,5.3,71.061,7.6738,126.7653,"23 km E of Kinablangan, Philippines",Moderate
2,us6000tg8z,2026-07-27 22:32:02.648,5.0,10.000,-7.5058,-13.4844,"112 km ENE of Georgetown, Saint Helena",Low
3,us6000tg6e,2026-07-27 19:03:38.391,4.5,426.772,28.1222,139.8936,"Bonin Islands, Japan region",Low
4,us6000tg5f,2026-07-27 17:47:01.325,4.5,116.626,36.6101,71.5913,"9 km SSE of Ashkāsham, Afghanistan",Low
...,...,...,...,...,...,...,...,...
572,us6000t8se,2026-06-28 03:39:21.783,4.6,10.000,37.9587,95.4541,"254 km SSE of Dunhuang, China",Low
573,us6000t8sa,2026-06-28 03:18:41.117,4.5,10.000,51.9357,176.2034,"229 km ESE of Attu Station, Alaska",Low
574,us6000t8s6,2026-06-28 02:59:20.784,5.1,76.884,-6.4130,147.7124,"21 km NW of Finschhafen, Papua New Guinea",Moderate
575,us6000tag6,2026-06-28 02:39:47.687,4.7,10.000,-9.7274,159.3959,"35 km W of Malango, Solomon Islands",Low
576,us6000t8xg,2026-06-28 02:22:10.778,4.6,10.000,-13.3173,-111.1977,central East Pacific Rise,Low

In [70]:
# Get existing event_ids already in the table
existing_ids = pd.read_sql('SELECT event_id FROM catastrophe', engine)['event_id'].tolist()

# Keep only rows whose event_id isn't already in the table
new_events = df_earthquakes[~df_earthquakes['event_id'].isin(existing_ids)]

# Load only the new rows
if not new_events.empty:
    new_events.to_sql('catastrophe', engine, if_exists='append', index=False)
    print(f"Inserted {len(new_events)} new rows.")
else:
    print("No new events to insert.")

No new events to insert.